services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:    
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  sqlserver_inventory:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Pass123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - inventory_data:/var/opt/mssql

  sqlserver_notification:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Pass123456"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - notification_data:/var/opt/mssql

  inventory.api:
    build:
      context: ./Inventory
      dockerfile: src/Dockerfile
    depends_on:
      - sqlserver_inventory
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver_inventory;Database=InventoryDb;User Id=sa;Password=Pass123456;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "5000:80"

  notification.api:
    build:
      context: ./Notification
      dockerfile: src/Dockerfile
    depends_on:
      - sqlserver_notification
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver_notification;Database=NotificationDb;User Id=sa;Password=Pass123456;TrustServerCertificate=True
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    ports:
      - "5001:80"

volumes:
  inventory_data:
  notification_data:
